### ISSUE TITLE
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given on new image

### ISSUE THREAD

**Issue by logopk** [jeanralphaviles/prometheus_speedtest#14]
Hi Jean-Ralph,

I tried your new image but the start fails with the following error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/prometheus_speedtest/prometheus_speedtest.py", line 136, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/prometheus_speedtest/prometheus_speedtest.py", line 130, in main
    logging.info('Starting HTTP server listening on %s:%s', FLAGS.address,
  File "/usr/local/lib/python3.8/site-packages/absl/logging/__init__.py", line 335, in info
    log(INFO, msg, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/absl/logging/__init__.py", line 476, in log
    _absl_logger.log(standard_level, msg, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/absl/logging/__init__.py", line 1038, in log
    super(ABSLLogger, self).log(level, msg, *args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1500, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1565, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given

Googling produce sth. similar here:

https://github.com/tensorflow/tensorflow/issues/35027

python 3.8 related?

Could you get your previous version back to docker hub please and tag it appropriately?

Thanks.

Peter

**Comment by logopk** [comment]
I changed FROM python:3-alpine to FROM python:3.7-alpine and the service starts.

**Comment by bennyb0y** [comment]
I received the same error: 

```
pi@pi:~ $ docker run --rm -i  -p 9516:9516/tcp jraviles/prometheus_speedtest:latest
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/prometheus_speedtest/prometheus_speedtest.py", line 136, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/prometheus_speedtest/prometheus_speedtest.py", line 130, in main
    logging.info('Starting HTTP server listening on %s:%s', FLAGS.address,
  File "/usr/local/lib/python3.8/site-packages/absl/logging/__init__.py", line 335, in info
    log(INFO, msg, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/absl/logging/__init__.py", line 476, in log
    _absl_logger.log(standard_level, msg, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/absl/logging/__init__.py", line 1038, in log
    super(ABSLLogger, self).log(level, msg, *args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1500, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1565, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by jeanralphaviles** [comment]
I'm not sure how that could've broken, unless python:3-alpine updated to Python 3.8. [requirements.txt](https://github.com/jeanralphaviles/prometheus_speedtest/blob/master/requirements.txt) pins the absl library at a specific version.

Anyways, it's a good idea to pin the Python version we're using to avoid this in the future. Thanks for the suggestion.

**Comment by jeanralphaviles** [comment]
Should now be fixed. I'll work on adding better test for this use case.
