### ISSUE TITLE
indCaller() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by jacekjaros** [jeanralphaviles/prometheus_speedtest#23]
I'm using venv (python 3.8.1)

```
$ pip install prometheus_speedtest
$ prometheus_speedtest
Traceback (most recent call last):
  File "/opt/exporters/speedtest/bin/prometheus_speedtest", line 11, in <module>
    load_entry_point('prometheus-speedtest==0.9.2', 'console_scripts', 'prometheus_speedtest')()
  File "/opt/exporters/speedtest/lib/python3.8/site-packages/prometheus_speedtest/prometheus_speedtest.py", line 137, in init
    app.run(main)
  File "/opt/exporters/speedtest/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/opt/exporters/speedtest/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/exporters/speedtest/lib/python3.8/site-packages/prometheus_speedtest/prometheus_speedtest.py", line 130, in main
    logging.info('Starting HTTP server listening on %s:%s', FLAGS.address,
  File "/opt/exporters/speedtest/lib/python3.8/site-packages/absl/logging/__init__.py", line 335, in info
    log(INFO, msg, *args, **kwargs)
  File "/opt/exporters/speedtest/lib/python3.8/site-packages/absl/logging/__init__.py", line 476, in log
    _absl_logger.log(standard_level, msg, *args, **kwargs)
  File "/opt/exporters/speedtest/lib/python3.8/site-packages/absl/logging/__init__.py", line 1038, in log
    super(ABSLLogger, self).log(level, msg, *args, **kwargs)
  File "/opt/python/3.8.1/lib/python3.8/logging/__init__.py", line 1500, in log
    self._log(level, msg, args, **kwargs)
  File "/opt/python/3.8.1/lib/python3.8/logging/__init__.py", line 1565, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
```

seems to be related to https://github.com/jeanralphaviles/prometheus_speedtest/issues/14

**Comment by neilmunday** [comment]
I have the same issue with Python 3.8. It appears to be due to a change in the logging API.

**Comment by neilmunday** [comment]
I should add that I am using the version of prometheus_speedtest from PyPi.

The issue is that this version requires `absl-py 0.7.1` which does not work with Python 3.8.

To work around until a new version of prometheus_speedtest is released:

Edit the `prometheus_speedtest-0.9.2-py3.8.egg-info/requires.txt` file and set `absl-py` to `0.9.0` as done on the master branch here.

Now update `absl-py`:

```
pip3 install -U absl-py
``` 

Now prometheus_speedtest should work.

Hope this helps.

**Comment by jacekjaros** [comment]
thanks @neilmunday 
absl-py update is solution i was looking for - now everything working fine.

**Comment by neilmunday** [comment]
@jacekjaros glad to hear it's working for you also.
