### ISSUE TITLE
Error while installing "No such file or directory: '***/requirements-dev.txt'"

### ISSUE THREAD

**Issue by pineapplehunter** [jeanralphaviles/prometheus_speedtest#57]
Hi I am having trouble installing this package.
When I `pip install prometheus-speedtest`, Iget an error like below.

```shell
# pip install prometheus-speedtest
Collecting prometheus-speedtest
  Using cached prometheus_speedtest-0.9.12.tar.gz (18 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-mlwcyal3/prometheus-speedtest_01a01e8fd40c4c96aa6b198bf83288ae/setup.py", line 58, in <module>
          extras_require={'dev': read_file('requirements-dev.txt')},
        File "/tmp/pip-install-mlwcyal3/prometheus-speedtest_01a01e8fd40c4c96aa6b198bf83288ae/setup.py", line 18, in read_file
          with open(os.path.join(here, rel_path), 'r', encoding='utf-8') as rel_file:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-mlwcyal3/prometheus-speedtest_01a01e8fd40c4c96aa6b198bf83288ae/requirements-dev.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

It seems that `requirements-dev.txt` file is not included in the package that pip downloades.

**Comment by jeanralphaviles** [comment]
Was able to reproduce. Bisect shows that this broke in 8d54872cf450f5e784d5e32a96216d4bde7b7431 on 2021-05-06.

```bash
python3 -m venv venv
source ./venv/bin/activate
pip install -r requirements-dev.txt
python3 setup.py sdist
pip install dist/*
deactivate
rm -r venv
rm -r dist
```
